### ISSUE TITLE
Random crashes regarding JavaScript (?)

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#266]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.0-21-g4851bae
GTK compile: 3.20.2
GTK run: 3.20.3
WebKit compile: 2.4.10
WebKit run: 2.4.10
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.0
```

> Is there a specific website which shows the problem?

oeticket.com, dailystar.co.uk

> If it is related to a crash on a website, do other WebKit-based browsers
exhibit the same symptoms? Other browsers include surf, midori, jumanji, dwb,
and sugar-browse.

not verified

**coredumpctl gdb 14511 (oeticket.com)**
```
(gdb) bt
#0  0x00007fe54af05a3c in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#1  0x00007fe54b0fc18a in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#2  0x00007fe54b0fb660 in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#3  0x00007fe54b10289d in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#4  0x00007fe54b0ffa5f in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#5  0x00007fe54b98acf2 in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#6  0x00007fe4f76f69c5 in ?? ()
#7  0x00007fe4c9307b48 in ?? ()
#8  0x00007fe4f7826492 in ?? ()
#9  0x0000000400000000 in ?? ()
#10 0x00007fe5377ba000 in ?? ()
#11 0x00007fe4b010a428 in ?? ()
#12 0x00007fffd8e56b30 in ?? ()
#13 0x00007fe4c9307ff8 in ?? ()
#14 0x00007fffd8e56b40 in ?? ()
#15 0x00007fffd8e56ac0 in ?? ()
#16 0x00007fe54a3adc23 in JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*, JSC::Register*) ()
   from /usr/lib/libjavascriptcoregtk-3.0.so.0
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

(gdb) info registers
rax            0x5820534f2063614d       6350167073903305037
rbx            0x3727390        57832336
rcx            0x0      0
rdx            0x7fe53775d208   140622454706696
rsi            0x7fe4a375ec90   140619971685520
rdi            0x7fe4a3492b00   140619968752384
rbp            0x7fffd8e56820   0x7fffd8e56820
rsp            0x7fffd8e56800   0x7fffd8e56800
r8             0x7      7
r9             0x30     48
r10            0x30     48
r11            0x2      2
r12            0x7fe4a3492b00   140619968752384
r13            0x7fe4a375ec90   140619971685520
r14            0x7fffd8e56a10   140736832301584
r15            0x7fe4a2cbb600   140619960530432
rip            0x7fe54af05a3c   0x7fe54af05a3c
eflags         0x10297  [ CF PF AF SF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

**coredumpctl gdb 25164 (dailystar.co.uk)**
```
(gdb) bt
#0  0x00007f9368e2ca3c in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#1  0x00007f936902318a in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#2  0x00007f9369022660 in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#3  0x00007f936902989d in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#4  0x00007f9369026a5f in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#5  0x00007f93698b1cf2 in ?? () from /usr/lib/libwebkitgtk-3.0.so.0
#6  0x00007f931561d9c5 in ?? ()
#7  0x00007f92deffdb38 in ?? ()
#8  0x00007f9315708e63 in ?? ()
#9  0x00000000021c76c4 in ?? ()
#10 0x00007f93556e0000 in ?? ()
#11 0x00007f92b64fdb48 in ?? ()
#12 0x00007fff48d8ae10 in ?? ()
#13 0x00007f92deffdff8 in ?? ()
#14 0x00007fff48d8ae20 in ?? ()
#15 0x00007fff48d8ada0 in ?? ()
#16 0x00007f93682d4c23 in JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*, JSC::Register*) ()
   from /usr/lib/libjavascriptcoregtk-3.0.so.0
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

(gdb) info registers
rax            0x73796c6961642e73       8320800986405023347
rbx            0x324b2e0        52736736
rcx            0x0      0
rdx            0x7f9355683208   140270769811976
rsi            0x7f92dc73b920   140268740524320
rdi            0x7f92dca72400   140268743894016
rbp            0x7fff48d8ab00   0x7fff48d8ab00
rsp            0x7fff48d8aae0   0x7fff48d8aae0
r8             0x3      3
r9             0x3c5    965
r10            0x422    1058
r11            0x2      2
r12            0x7f92dca72400   140268743894016
r13            0x7f92dc73b920   140268740524320
r14            0x7fff48d8acf0   140734415547632
r15            0x7f92dc261c00   140268735437824
rip            0x7f9368e2ca3c   0x7f9368e2ca3c
eflags         0x10287  [ CF PF SF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

On oeticket the crashes happened during the checkout process.

On dailystar, crashes happen very consistently upon scrolling the site. Apparently the crashes may be avoided by disabling JS in uzbl.

**Comment by mathstuf** [comment]
Not much we can do about it I imagine unless other browsers don't crash. FYI, there is 2.4.11 now. It may have fixed some things.

**Comment by GSI** [comment]
Thanks for the hint! After updating accordingly, I was unable to reproduce the crash.

I was still able to cause a crash by randomly navigating the site, but this time the core dump was emptly, so that could have been caused by some other error.

Would it be possible to catch such things in uzbl and avoid the whole browser crashing?

**Comment by mathstuf** [comment]
If something segfaults inside of JavaScriptCore, the best we could do is force JS off for that instance, but I don't think running around with a NULL dereference or whatever caused the segfault to occur hanging off in the back is a good idea. Plus, I'm not sure how we'd get the code pointer to go back to uzbl with the proper "something went wrong" state. Basically, programs shouldn't segfault and trying to fix such things programmatically is harder than fixing the root cause in the first place :) .

**Comment by GSI** [comment]
Sounds reasonable. Also, most of uzbl's users should understand that - instead of blaming the browser. Closing.
