### ISSUE TITLE
Segfault with trailing backslash

### ISSUE THREAD

**Issue by mathstuf** [uzbl/uzbl#286]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.0-12-ge5fe801
GTK compile: 3.20.1
GTK run: 3.21.1
WebKit compile: 2.4.10
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.1
```

@keis Seems to be something about escaping rules :) . Search for `foo\`  and watch it crash.

Backtrace:

```
(gdb) bt
#0  0x00007ffff1fc4635 in raise () at /lib64/libc.so.6
#1  0x00007ffff1fc623a in abort () at /lib64/libc.so.6
#2  0x00007ffff20070f0 in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff200f0bf in free_check () at /lib64/libc.so.6
#4  0x00007ffff20133a7 in free () at /lib64/libc.so.6
#5  0x00007ffff290205e in g_free () at /lib64/libglib-2.0.so.0
#6  0x000000000040bf13 in uzbl_commands_args_free (argv=0xd98240) at src/commands.c:151
#7  0x000000000040c219 in uzbl_commands_run (cmd=0xe01270 "search find foo\\", result=0x7fc640) at src/commands.c:251
#8  0x0000000000415124 in run_command (item=0xe09de0, data=0x0) at src/io.c:382
#9  0x000000000041ec15 in uzbl_rb_async_queue_watch_dispatch (source=0x6f6220, callback=0x4150c7 <run_command>, user_data=0x0) at src/3p/async-queue-source/rb-async-queue-watch.c:85
#10 0x00007ffff28fc7ea in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#11 0x00007ffff28fcba0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#12 0x00007ffff28fcec2 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#13 0x00007ffff497c7b5 in gtk_main () at /lib64/libgtk-3.so.0
#14 0x000000000040b300 in main (argc=1, argv=0x7fffffffcca8) at src/uzbl-core.c:347
```

**Comment by keis** [comment]
Hmm. I can't reproduce that I tried both the / binding and sending "search find foo\" over the socket.

**Comment by mathstuf** [comment]
K. I'll debug tomorrow then :) .
