### ISSUE TITLE
Crash when enabling verbose output

### ISSUE THREAD

**Issue by mathstuf** [uzbl/uzbl#368]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.1-163-g4fbf619
GTK compile: 3.22.10
GTK run: 3.22.10
WebKit compile: 2.16.0
WebKit run: 2.16.0
WebKit2: 1
libsoup compile: 2.56.0
libsoup run: 2.56.0
```

Looks like the window isn't valid at the point where we try to dump information about it.

```
#0  0x00007ffff3a0b5e2 in _gdk_window_has_impl () at /lib64/libgdk-3.so.0
#1  0x00007ffff3a41c3e in gdk_x11_window_get_xid () at /lib64/libgdk-3.so.0
#2  0x000000000040cea2 in main (argc=1, argv=0x7fffffffb308) at src/uzbl-core.c:410
```

**Comment by keis** [comment]
I don't see this and frome the trace it looks X11 related and I'm currently running on wayland so maybe that's why
